/** ATTENTION!!! This file is automatically generated, changes made here will be lost. */
export type TStyles = {
  'button': string;
  'icon': string;
  'primary': string;
  'root': string;
  'secondary': string;
  'success': string;
};

export type TClassNames = keyof TStyles;

declare const styles: TStyles;

export default styles;
