/**
 * Typed SCSS Modules Configuration.
 */
export const config = {
  banner:
    "/** ATTENTION!!! This file is automatically generated, changes made here will be lost. */",
  exportType: "default",
  exportTypeInterface: "TStyles",
  exportTypeName: "TClassNames",
  logLevel: "error",
};
