import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "./_components/Header";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { ELanguage } from "./_components/LanguageSelect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: LayoutProps<"/[lang]">) {
  const { children, params } = props;
  const messages = await getMessages();
  const { lang } = await params;

  return (
    <html lang={lang}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider messages={messages}>
          <div className="min-h-screen bg-gray-50 flex flex-col font-sans text-gray-900">
            <Header language={lang as ELanguage} />
            <main className="flex-1 flex flex-col">{children}</main>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
