/** ATTENTION!!! This file is automatically generated, changes made here will be lost. */
export type TStyles = {
  'chevron': string;
  'opened': string;
  'root': string;
  'value': string;
};

export type TClassNames = keyof TStyles;

declare const styles: TStyles;

export default styles;
