/** ATTENTION!!! This file is automatically generated, changes made here will be lost. */
export type TStyles = {
  'opened': string;
  'popup': string;
  'root': string;
};

export type TClassNames = keyof TStyles;

declare const styles: TStyles;

export default styles;
