/** ATTENTION!!! This file is automatically generated, changes made here will be lost. */
export type TStyles = {
  'check': string;
  'option': string;
  'root': string;
  'row': string;
  'selected': string;
};

export type TClassNames = keyof TStyles;

declare const styles: TStyles;

export default styles;
